import React from 'react'
import WorldMap from "react-svg-worldmap";

export default function MapChart() {
    const data = [
        { country: "AF", value: '' }, { country: "AL", value: '' },
        { country: "DZ", value: '' }, { country: "AS", value: '' },
        { country: "AD", value: '' }, { country: "AO", value: '' },
        { country: "AG", value: '' }, { country: "AR", value: '' },
        { country: "AM", value: '' }, { country: "AU", value: '' },
        { country: "AT", value: '' }, { country: "AZ", value: '' },
        { country: "BS", value: '' }, { country: "BH", value: '' },
        { country: "BD", value: '' }, { country: "BB", value: '' },
        { country: "BY", value: '' }, { country: "BE", value: '' },
        { country: "BZ", value: '' }, { country: "BJ", value: '' },
        { country: "BT", value: '' }, { country: "BO", value: '' },
        { country: "BA", value: '' }, { country: "BW", value: '' },
        { country: "BR", value: '' }, { country: "BN", value: '' },
        { country: "BG", value: '' }, { country: "BF", value: '' },
        { country: "BI", value: '' }, { country: "CV", value: '' },
        { country: "KH", value: '' }, { country: "CM", value: '' },
        { country: "CA", value: '' }, { country: "CF", value: '' },
        { country: "TD", value: '' }, { country: "CL", value: '' },
        { country: "CN", value: '' }, { country: "CO", value: '' },
        { country: "KM", value: '' }, { country: "CG", value: '' },
        { country: "CD", value: '' }, { country: "CR", value: '' },
        { country: "CI", value: '' }, { country: "HR", value: '' },
        { country: "CU", value: '' }, { country: "CY", value: '' },
        { country: "CZ", value: '' }, { country: "DK", value: '' },
        { country: "DJ", value: '' }, { country: "DM", value: '' },
        { country: "DO", value: '' }, { country: "EC", value: '' },
        { country: "EG", value: '' }, { country: "SV", value: '' },
        { country: "GQ", value: '' }, { country: "ER", value: '' },
        { country: "EE", value: '' }, { country: "SZ", value: '' },
        { country: "ET", value: '' }, { country: "FJ", value: '' },
        { country: "FI", value: '' }, { country: "FR", value: '' },
        { country: "GA", value: '' }, { country: "GM", value: '' },
        { country: "GE", value: '' }, { country: "DE", value: '' },
        { country: "GH", value: '' }, { country: "GR", value: '' },
        { country: "GD", value: '' }, { country: "GT", value: '' },
        { country: "GN", value: '' }, { country: "GW", value: '' },
        { country: "GY", value: '' }, { country: "HT", value: '' },
        { country: "HN", value: '' }, { country: "HU", value: '' },
        { country: "IS", value: '' }, { country: "IN", value: '' },
        { country: "ID", value: '' }, { country: "IR", value: '' },
        { country: "IQ", value: '' }, { country: "IE", value: '' },
        { country: "IL", value: '' }, { country: "IT", value: '' },
        { country: "JM", value: '' }, { country: "JP", value: '' },
        { country: "JO", value: '' }, { country: "KZ", value: '' },
        { country: "KE", value: '' }, { country: "KI", value: '' },
        { country: "KP", value: '' }, { country: "KR", value: '' },
        { country: "KW", value: '' }, { country: "KG", value: '' },
        { country: "LA", value: '' }, { country: "LV", value: '' },
        { country: "LB", value: '' }, { country: "LS", value: '' },
        { country: "LR", value: '' }, { country: "LY", value: '' },
        { country: "LI", value: '' }, { country: "LT", value: '' },
        { country: "LU", value: '' }, { country: "MG", value: '' },
        { country: "MW", value: '' }, { country: "MY", value: '' },
        { country: "MV", value: '' }, { country: "ML", value: '' },
        { country: "MT", value: '' }, { country: "MH", value: '' },
        { country: "MR", value: '' }, { country: "MU", value: '' },
        { country: "MX", value: '' }, { country: "FM", value: '' },
        { country: "MD", value: '' }, { country: "MC", value: '' },
        { country: "MN", value: '' }, { country: "ME", value: '' },
        { country: "MA", value: '' }, { country: "MZ", value: '' },
        { country: "MM", value: '' }, { country: "NA", value: '' },
        { country: "NR", value: '' }, { country: "NP", value: '' },
        { country: "NL", value: '' }, { country: "NZ", value: '' },
        { country: "NI", value: '' }, { country: "NE", value: '' },
        { country: "NG", value: '' }, { country: "MK", value: '' },
        { country: "NO", value: '' }, { country: "OM", value: '' },
        { country: "PK", value: '' }, { country: "PW", value: '' },
        { country: "PA", value: '' }, { country: "PG", value: '' },
        { country: "PY", value: '' }, { country: "PE", value: '' },
        { country: "PH", value: '' }, { country: "PL", value: '' },
        { country: "PT", value: '' }, { country: "QA", value: '' },
        { country: "RO", value: '' }, { country: "RU", value: '' },
        { country: "RW", value: '' }, { country: "KN", value: '' },
        { country: "LC", value: '' }, { country: "VC", value: '' },
        { country: "WS", value: '' }, { country: "SM", value: '' },
        { country: "ST", value: '' }, { country: "SA", value: '' },
        { country: "SN", value: '' }, { country: "RS", value: '' },
        { country: "SC", value: '' }, { country: "SL", value: '' },
        { country: "SG", value: '' }, { country: "SK", value: '' },
        { country: "SI", value: '' }, { country: "SB", value: '' },
        { country: "SO", value: '' }, { country: "ZA", value: '' },
        { country: "SS", value: '' }, { country: "ES", value: '' },
        { country: "LK", value: '' }, { country: "SD", value: '' },
        { country: "SR", value: '' }, { country: "SE", value: '' },
        { country: "CH", value: '' }, { country: "SY", value: '' },
        { country: "TW", value: '' }, { country: "TJ", value: '' },
        { country: "TZ", value: '' }, { country: "TH", value: '' },
        { country: "TL", value: '' }, { country: "TG", value: '' },
        { country: "TO", value: '' }, { country: "TT", value: '' },
        { country: "TN", value: '' }, { country: "TR", value: '' },
        { country: "TM", value: '' }, { country: "TV", value: '' },
        { country: "UG", value: '' }, { country: "UA", value: '' },
        { country: "AE", value: '' }, { country: "GB", value: '' },
        { country: "US", value: '' }, { country: "UY", value: '' },
        { country: "UZ", value: '' }, { country: "VU", value: '' },
        { country: "VA", value: '' }, { country: "VE", value: '' },
        { country: "VN", value: '' }, { country: "YE", value: '' },
        { country: "ZM", value: '' }, { country: "ZW", value: '' }
    ];

    return (
        <div className="chartsvg flex">
            <WorldMap
                color="grey"
                title="Top 10 Populous Countries"
                value-suffix="people"
                size="lg"
                data={data}
            />
        </div>
    );
}
